# Generated by Django 3.1.7 on 2021-03-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(max_length=250, verbose_name='Contenido'),
        ),
    ]
